-- Create the vetClinic Database

DROP DATABASE IF EXISTS vetClinic;
CREATE DATABASE vetClinic;
USE vetClinic;

-- Create Tables

CREATE TABLE IF NOT EXISTS `vetClinic`.`Clinic` (
  `CLINIC_NUM` INT NOT NULL AUTO_INCREMENT,
  `CLINIC_ADDRESS` VARCHAR(255) NOT NULL,
  `CLINIC_CITY` VARCHAR(50) NOT NULL,
  `CLINIC_STATE` CHAR(2) NOT NULL,
  `CLINIC_ZIP` VARCHAR(10) NOT NULL,
  `CLINIC_TEL` VARCHAR(10) NOT NULL,
  `CLINIC_FAX` VARCHAR(10) NOT NULL,
  `CLINIC_MANAGER` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CLINIC_NUM`)
  );

CREATE TABLE IF NOT EXISTS `vetClinic`.`Pet_Owners` (
  `OWNER_ID` INT NOT NULL,
  `CLINIC_NUM` INT NOT NULL,
  `OWNER_FNAME` VARCHAR(45) NOT NULL,
  `OWNER_LNAME` VARCHAR(45) NOT NULL,
  `OWNER_ADDRESS` VARCHAR(255) NOT NULL,
  `OWNER_CITY` VARCHAR(45) NOT NULL,
  `OWNER_STATE` CHAR(2) NOT NULL,
  `OWNER_ZIP` VARCHAR(10) NOT NULL,
  `OWNER_PHONE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OWNER_ID`),
  INDEX `CLINIC_NUM_idx` (`CLINIC_NUM` ASC) VISIBLE,
  CONSTRAINT `CLINIC_NUM`
    FOREIGN KEY (`CLINIC_NUM`)
    REFERENCES `vetClinic`.`Clinic` (`CLINIC_NUM`)
);